name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo bash build.sh


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto build"
          files: |
            /output/*

